### PR TITLE
scheduler: Fix cupsd activated on-demand via socket

### LINKED ISSUE #985: [2.4.9 regression] cupsd don't start when only Listen /path/to/domain/socket is set in conf
**Describe the bug**
Setting cupsd to listen only on socket path prevents cups daemon from starting. It worked in 2.4.8 and before and stopped working in 2.4.9.

If the only `Listen` directive in `cupsd.conf` is set to socket path like:
`Listen /run/cups/cups.sock`
then cupsd daemon fails to start when running from systemd:
`cups.service: Failed with result 'protocol'.`

The cups error log shows:
`No valid Listen or Port lines were found in the configuration file.`

**To Reproduce**
Steps to reproduce the behavior (on ArchLinux):
1. Go to `/etc/cups/cupsd.conf` and  remove any other `Listen` directive than `Listen /run/cups/cups.sock`
2. Run `systemct start cups.socket`
3. Run `systemctl start cups`
4. See `cups.service: Failed with result 'protocol'.`  and `No valid Listen or Port lines were found in the configuration file.` error messages

**Expected behavior**
I expect cupsd service to start like before

**System Information:**
OS: ArchLinux
Cups 2.4.9

**Additional context**
By reading changelog I presume it's somewhat related to https://github.com/OpenPrinting/cups/commit/a436956f374b0fd7f5da9df482e4f5840fa1c0d2 but the listening on socket functionality is still present in cups and I don't know what users are supposed to do to make it work.

### PR DESCRIPTION
**Pull request by zdohnal**
If only the expected cups.sock is set as listener in cupsd.conf, the array Listeners was NULL. To prevent copying the code, do the array allocation earlier and have only one check for Listeners, in service_checkin() which is run every time cupsd starts.

Fixes #985

### CODE REVIEW

File: scheduler/conf.c [hunk 1]
```diff
@@ -1043,32 +1054,6 @@ cupsdReadConfiguration(void)
     }
   }
 
- /*
```
Comment (michaelrsweet) [inline scheduler/conf.c:1046]: OK, we don't want to remove this check because a cupsd without listeners cannot be used and that is a fatal condition.

File: scheduler/conf.c [hunk 2]
```diff
@@ -558,6 +558,17 @@ cupsdReadConfiguration(void)
 
   cupsdDeleteAllListeners();
 
+ /*
+  * Allocate Listeners array
+  */
+  Listeners = cupsArrayNew(NULL, NULL);
```
Comment (michaelrsweet) [inline scheduler/conf.c:564]: Minor nit - add a blank line after the comment...

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
Thanks for figuring this out - it didn't occur to me to make sure the Listeners array was allocated... Once you address my two comments this is ready to go.

File: scheduler/conf.c (hunk 1 above)
Comment (zdohnal) [reply scheduler/conf.c:1046]: The check is moved into ```service_checkin()```, which should cover both cases - if there are no valid listeners in cupsd.conf and if there are no listeners from outer system (like systemd, launchd, upstart).

I've checked the code once more and what I see as redundant (in case there is no listener) is loading all data from disk - but this happens in case cups.sock is set as only listener as well.

I would not like to have the same code on two places, but moving service_checkin and service_checkout into cupsdReadConfiguration() does not make sense as well...

Comment (zdohnal) [reply scheduler/conf.c:1046]: And it would free us the ifdef-fu :)

Comment (michaelrsweet) [reply scheduler/conf.c:1046]: But service_checkin is only used when a) you build with launchd/systemd/upstart, and b) when you run cupsd with the "I'm running from launchd/systemd/upstart" option. So we need this check in both places to make sure we don't end up with a non-functional instance of cupsd.

Comment (zdohnal) [reply scheduler/conf.c:1046]: It does not seem to be the case - IIUC it is called only on one place in main.c:

```
 588  /*
 589   * If we were started on demand by launchd or systemd get the listen sockets
 590   * file descriptors... 
 591   */
 592 
 593   service_checkin();    
 594   service_checkout(0);
```

this is not guarded by ifdef or OnDemand option. Then the function itself has most of code guarded by OnDemand and ifdefs, but the last check for Listeners is unguarded:

```
2038 #endif /* HAVE_LAUNCHD */
2039 
2040   if (cupsArrayCount(Listeners) == 0)
2041   {
2042    /*
2043     * No listeners!
2044     */
2045 
2046     cupsdLogMessage(CUPSD_LOG_EMERG, "service_checkin: No listener sockets present.");
2047 
2048    /*
2049     * Commit suicide...
2050     */
2051 
2052     cupsdEndProcess(getpid(), 0);
2053   }
```

thus, since ```service_checkin()``` does not seem guarded in ```main()```, the check is called every time cupsd is loaded, regardless whether it is OnDemand or other.

Comment (michaelrsweet) [reply scheduler/conf.c:1046]: OK, then let's strip the "service_checkin" prefix from the message.

File: scheduler/conf.c (hunk 2 above)
Comment (zdohnal) [reply scheduler/conf.c:565]: Resolved, thanks!
