### PR TITLE
cups/dest.c: Raise timeout _CUPS_DNSSD_GET_DESTS

### LINKED ISSUE #751: Timeout for cupsEnumDests() too short (using Linux with Avahi)
**Describe the bug**
Already for some time `lpstat -e` only lists the permanent CUPS queues, not discovered IPP printers on which CUPS can print using a temporary queue. Investigating the code revealed that the timeout for asynchronous Avahi resolving in the `cupsGetDests()` API function which uses the internal (static) function `cups_get_dests()` with its is too short.

In `cups/dest.c` is defined:
```
#  define _CUPS_DNSSD_GET_DESTS 250     /* Milliseconds for cupsGetDests */
```
setting it to
```
#  define _CUPS_DNSSD_GET_DESTS 1000    /* Milliseconds for cupsGetDests */
```
solves the problem. Now the loop in `cups_get_dests()` stays running long enough for the asynchronous Avahi resolving calls for the discovered IPP print destinatiuons to finish and the results being caught.

I have found out that for timeouts < 620 no resolving process at all is finishing in time and so no discovered IPP print destinations get listed and with only a little more than 620 msec, for example 630 msec, all the resolving processes finish and all the resukts get taken into account, making all printers listed (I had 27 in the test). Th 100 msec seem to be a very safe bet.

**To Reproduce**
Without the fix
```
lpstat -l -e
```
ouputs one line for each permanent CUPS queue, so if `lpstat -v` outputs a line like
```
device for testprinter: ipps://hp8730._ipps._tcp.local/
``` 
the `lpstat -l -e` gives the corresponding line
```
testprinter permanent ipp://localhost/printers/testprinter ipps://till-x1yoga.local:8002/ipp/print/hp8730
```
So we get one line for each permanent CUPS queue and **no further lines for discovered printers**.

With the timeout corrected and with IPP print destinations available (The `driverless` command lists all of them) the command
```
lpstat -l -e
```
has more output, in addition to the lines for permanent queues there are lines for discovered IPP printers.
For each output line of `driverless` like
```
ipps://test._ipps._tcp.local/
```
you get a line
```
test network none ipps://test._ipps._tcp.local/
```
(at least if no permanent queue was created for this URI.

**System Information:**
 - OS is Ubuntu 23.04 and 23.10
 - CUPS is version 2.4.2 or later, up to the current GIT master (`libcups.so.2`)
 - Avahi is version 0.8

### PR DESCRIPTION
**Pull request by zdohnal**
The current timeout is not able to list all network devices if there are many IPP services on mDNS (the tested number is 165 services).

Raising the timeout to 1s does not slow libcups if there are less services (Avahi returns earlier) or if Avahi does not run on the system (libcups cannot create an Avahi client in that case), and provides time frame for getting reasonable amount of IPP services (big enterprise servers will use permanent queues and printer profiles than mDNS).

Fixes #751

### CODE REVIEW

File: cups/dest.c [hunk 1]
```diff
@@ -40,7 +40,7 @@
 #  define kUseLastPrinter	CFSTR("UseLastPrinter")
 #endif // __APPLE__
 
-#define _CUPS_DNSSD_GET_DESTS	250	// Milliseconds for cupsGetDests
+#define _CUPS_DNSSD_GET_DESTS	1000	// Milliseconds for cupsGetDests
```
Comment (tillkamppeter) [inline cups/dest.c:43]: @michaelrsweet suggested up to 10 sec (would be 10000) here. Would also not cause any problem and cover even more weird systems ...

Comment (michaelrsweet) [reply cups/dest.c:43]: @tillkamppeter I suggested 10 seconds for `lpstat -e`, 1 second for `cupsGetDests` seems like a safer limit for applications, especially when `cupsEnumDests` is a better choice...

**Review by michaelrsweet — APPROVED** [review]
LGTM

File: cups/dest.c (hunk 1 above)
Comment (zdohnal) [reply cups/dest.c:43]: @tillkamppeter there is 1 sec in the description so I used that for that reason as well :) .
