### PR TITLE
cgi: Fix checkbox support (fixes #1008)

### LINKED ISSUE #1008: Unable to enable Sharing when modifying a printer from the CUPS web UI
**Describe the bug**
Unable to enable Sharing when adding or modifying a printer from the CUPS web UI (CUPS version 2.4.10).

**To Reproduce**
From the CUPS web UI in a browser:
Administration tab -> Manage Printers -> choose printer -> Modify Printer -> Continue
choose/tick Sharing: Share This Printer
continue onwards to complete modifying printer

**Expected behaviour**
Printer should be shared.

**Actual behaviour**
Printer is not shared.

**Workaround**
Manually modify `/etc/cups/printers.conf` and change "Shared No" to "Shared Yes"

**System Information:**
 - OS: Linux OpenWrt 23.05.3 aarch64 (Raspberry Pi 4)
 - Browser: Safari 16.6.1 on MacOS 11.7.10 Big Sur
 - CUPS version: 2.4.10

**Relevant Logs**
Observed logs when turning sharing off and then back on again from CUPS web UI (after above workaround).

`/var/log/cups/error_log`
```
D [11/Jul/2024:10:15:17 +1000] [CGI] cgiSetVariable: PRINTER_IS_SHARED=\"\"
I [11/Jul/2024:10:15:17 +1000] Setting USB printer-is-shared to 0 (was 1.)
```
```
D [11/Jul/2024:10:17:26 +1000] [CGI] cgiSetVariable: PRINTER_IS_SHARED=\"on\"
I [11/Jul/2024:10:17:26 +1000] Setting USB printer-is-shared to 0 (was 0.)
```
**Additional context**
Looking at the code changes in this [commit](https://github.com/OpenPrinting/cups/commit/d847b53e88d64faf2c4a0bf8fc19f7112060778c#diff-325c4165c1104f3e60bdbbcd3e6f2ff417e25cdb483688350a5f77d39699dcd4), possibly the handling for string "on" was removed at `cgi-bin/admin.c`?

```
1169 -    var = cgiGetCheckbox("printer_is_shared");
1170 -    ippAddBoolean(request, IPP_TAG_PRINTER, "printer-is-shared",
1171 -                  var && (!strcmp(var, "1") || !strcmp(var, "on")));
1162 +    ippAddBoolean(request, IPP_TAG_PRINTER, "printer-is-shared", cgiGetCheckbox("PRINTER_IS_SHARED"));
```

### PR DESCRIPTION
**Pull request by zdohnal**
There was a change in CGI script regarding checkboxes, however it did not propagate into templates. Based on the change, the only valid check was if the variable value was `checkbox`, but some browsers (at least Firefox) send `on` as a default value for input form of type checkbox.

Additionally, the value `checkbox` looks like typo, because we use `checked` as value for checkboxes in admin CGI program, so I updated `cgiGetCheckbox()` as well.

To fix the behavior, we have to set `VALUE="CHECKED"` into every tag in every templates for all checkboxes - this value will be sent in the input form, so it will properly match with `cgiGetCheckbox()` logic now.

In the end, I have found out "Preserve Job History" checkbox from template was handled as text field, which did not look correct, and implemented default values for dependent options.

Fixes #1008

### CODE REVIEW

File: cgi-bin/admin.c [hunk 1]
```diff
@@ -1394,7 +1396,7 @@ do_config_server(http_t *http)		/* I - HTTP connection */
     if ((current_preserve_job_files = cupsGetOption("PreserveJobFiles",
                                                     num_settings,
 						    settings)) == NULL)
-      current_preserve_job_files = "1d";
+      current_preserve_job_files = "86400";
```
Comment (michaelrsweet) [inline cgi-bin/admin.c:1399]: Seems unnecessary - the cupsd.conf loader converts "1d" to 86400...

File: templates/add-printer.tmpl [hunk 2]
```diff
@@ -32,7 +32,7 @@
 </TR>
 <TR>
 <TH CLASS="label">Sharing:</TH>
-<TD><INPUT TYPE="CHECKBOX" NAME="PRINTER_IS_SHARED" ID="PRINTER_IS_SHARED" {PRINTER_IS_SHARED=1?CHECKED:}>
+<TD><INPUT TYPE="CHECKBOX" NAME="PRINTER_IS_SHARED" ID="PRINTER_IS_SHARED" VALUE="CHECKED" {PRINTER_IS_SHARED=1?CHECKED:}>
```
Comment (michaelrsweet) [inline templates/add-printer.tmpl:35]: The "VALUE" here is not valid.

File: templates/admin.tmpl [hunk 3]
```diff
@@ -38,36 +38,36 @@
 
     <P><A HREF="/admin/">Advanced <SMALL>&#x25bc;</SMALL></A><BR>
     <INPUT TYPE="HIDDEN" NAME="OP" VALUE="config-server">
-    <INPUT TYPE="HIDDEN" NAME="ADVANCEDSETTINGS" VALUE="YES">
-    <INPUT TYPE="CHECKBOX" NAME="SHARE_PRINTERS" ID="SHARE_PRINTERS" {?share_printers}><LABEL FOR="SHARE_PRINTERS"> Share printers connected to this system</LABEL><BR>
+    <INPUT TYPE="HIDDEN" NAME="ADVANCEDSETTINGS" VALUE="CHECKED">
+    <INPUT TYPE="CHECKBOX" NAME="SHARE_PRINTERS" ID="SHARE_PRINTERS" VALUE="CHECKED" {?share_printers}><LABEL FOR="SHARE_PRINTERS"> Share printers connected to this system</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/admin.tmpl:42]: VALUE for checkbox is not valid.

File: templates/admin.tmpl [hunk 4]
```diff
@@ -38,36 +38,36 @@
...
-    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="CHECKBOX" NAME="BROWSE_WEB_IF" ID="BROWSE_WEB_IF" {?browse_web_if}><LABEL FOR="BROWSE_WEB_IF">  Advertise web interface</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="REMOTE_ADMIN" ID="REMOTE_ADMIN" {?remote_admin}><LABEL FOR="REMOTE_ADMIN">  Allow remote administration</LABEL><BR>
-    {have_gssapi?<INPUT TYPE="CHECKBOX" NAME="KERBEROS" ID="KERBEROS" {?kerberos}><LABEL FOR="KERBEROS"> Use Kerberos authentication (<A HREF="/help/kerberos.html?TOPIC=Getting+Started">FAQ</A>)</LABEL><BR>:}
-    <INPUT TYPE="CHECKBOX" NAME="USER_CANCEL_ANY" ID="USER_CANCEL_ANY" {?user_cancel_any}><LABEL FOR="USER_CANCEL_ANY">  Allow users to cancel any job (not just their own)</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="PRESERVE_JOBS" ID="PRESERVE_JOBS" {?preserve_jobs}><LABEL FOR="PRESERVE_JOBS">  Preserve job history</LABEL><BR>
+    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="CHECKBOX" NAME="REMOTE_ANY" ID="REMOTE_ANY" VALUE="CHECKED" {?remote_any}><LABEL FOR="REMOTE_ANY">  Allow printing from the Internet</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/admin.tmpl:45]: VALUE for checkbox is not valid.

File: templates/admin.tmpl [hunk 5]
```diff
@@ -38,36 +38,36 @@
...
+    <INPUT TYPE="CHECKBOX" NAME="PRESERVE_JOBS" ID="PRESERVE_JOBS" VALUE="CHECKED" {?preserve_jobs}><LABEL FOR="PRESERVE_JOBS">  Preserve job history</LABEL><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Maximum jobs (0 for no limit)\:
     <INPUT TYPE="TEXT" NAME="MAX_JOBS" VALUE="{?max_jobs}" SIZE="6"><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Retain Metadata\:
     <INPUT TYPE="TEXT" NAME="PRESERVE_JOB_HISTORY" VALUE="{?preserve_job_history}" SIZE="6"><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Retain Documents\:
     <INPUT TYPE="TEXT" NAME="PRESERVE_JOB_FILES" VALUE="{?preserve_job_files}" SIZE="6"><BR>
-    <INPUT TYPE="CHECKBOX" NAME="DEBUG_LOGGING" ID="DEBUG_LOGGING" {?debug_logging}><LABEL FOR="DEBUG_LOGGING">  Save debugging information for troubleshooting</LABEL><BR>
+    <INPUT TYPE="CHECKBOX" NAME="DEBUG_LOGGING" ID="DEBUG_LOGGING" VALUE="CHECKED" {?debug_logging}><LABEL FOR="DEBUG_LOGGING">  Save debugging information for troubleshooting</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/admin.tmpl:57]: VALUE for checkbox is not valid.

File: templates/admin.tmpl [hunk 6]
```diff
@@ -38,36 +38,36 @@
...
-    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="CHECKBOX" NAME="REMOTE_ANY" ID="REMOTE_ANY" {?remote_any}><LABEL FOR="REMOTE_ANY">  Allow printing from the Internet</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="REMOTE_ADMIN" ID="REMOTE_ADMIN" {?remote_admin}><LABEL FOR="REMOTE_ADMIN">  Allow remote administration</LABEL><BR>
-    {have_gssapi?<INPUT TYPE="CHECKBOX" NAME="KERBEROS" ID="KERBEROS" {?kerberos}><LABEL FOR="KERBEROS">  Use Kerberos authentication (<A HREF="/help/kerberos.html?TOPIC=Getting+Started">FAQ</A>)</LABEL><BR>:}
-    <INPUT TYPE="CHECKBOX" NAME="USER_CANCEL_ANY" ID="USER_CANCEL_ANY" {?user_cancel_any}><LABEL FOR="USER_CANCEL_ANY">  Allow users to cancel any job (not just their own)</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="DEBUG_LOGGING" ID="DEBUG_LOGGING" {?debug_logging}><LABEL FOR="DEBUG_LOGGING">  Save debugging information for troubleshooting</LABEL></P>
+    <INPUT TYPE="CHECKBOX" NAME="SHARE_PRINTERS" ID="SHARE_PRINTERS" VALUE="CHECKED" {?share_printers}><LABEL FOR="SHARE_PRINTERS"> Share printers connected to this system</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/admin.tmpl:65]: VALUE for checkbox is not valid.

File: templates/da/add-printer.tmpl [hunk 7]
```diff
@@ -32,7 +32,7 @@
 </TR>
 <TR>
 <TH CLASS="label">Deling:</TH>
-<TD><INPUT TYPE="CHECKBOX" NAME="PRINTER_IS_SHARED" ID="PRINTER_IS_SHARED" {PRINTER_IS_SHARED=1?CHECKED:}>
+<TD><INPUT TYPE="CHECKBOX" NAME="PRINTER_IS_SHARED" ID="PRINTER_IS_SHARED" VALUE="CHECKED" {PRINTER_IS_SHARED=1?CHECKED:}>
```
Comment (michaelrsweet) [inline templates/da/add-printer.tmpl:35]: VALUE for checkbox is not valid.

File: templates/da/admin.tmpl [hunk 8]
```diff
@@ -38,36 +38,36 @@
 
     <P><A HREF="/admin/">Avanceret <SMALL>&#x25bc;</SMALL></A><BR>
     <INPUT TYPE="HIDDEN" NAME="OP" VALUE="config-server">
-    <INPUT TYPE="HIDDEN" NAME="ADVANCEDSETTINGS" VALUE="YES">
-    <INPUT TYPE="CHECKBOX" NAME="SHARE_PRINTERS" ID="SHARE_PRINTERS" {?share_printers}><LABEL FOR="SHARE_PRINTERS"> Del printere som er forbundet til systemet</LABEL><BR>
+    <INPUT TYPE="HIDDEN" NAME="ADVANCEDSETTINGS" VALUE="CHECKED">
+    <INPUT TYPE="CHECKBOX" NAME="SHARE_PRINTERS" ID="SHARE_PRINTERS" VALUE="CHECKED" {?share_printers}><LABEL FOR="SHARE_PRINTERS"> Del printere som er forbundet til systemet</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/da/admin.tmpl:42]: VALUE for checkbox is not valid.

File: templates/da/admin.tmpl [hunk 9]
```diff
@@ -38,36 +38,36 @@
...
-    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="CHECKBOX" NAME="BROWSE_WEB_IF" ID="BROWSE_WEB_IF" {?browse_web_if}><LABEL FOR="BROWSE_WEB_IF">  Annoncér webgrænseflade</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="REMOTE_ADMIN" ID="REMOTE_ADMIN" {?remote_admin}><LABEL FOR="REMOTE_ADMIN">  Tillad fjernadministration</LABEL><BR>
-    {have_gssapi?<INPUT TYPE="CHECKBOX" NAME="KERBEROS" ID="KERBEROS" {?kerberos}><LABEL FOR="KERBEROS"> Brug Kerberos-autentifikation (<A HREF="/help/kerberos.html?TOPIC=Getting+Started">FAQ</A>)</LABEL><BR>:}
-    <INPUT TYPE="CHECKBOX" NAME="USER_CANCEL_ANY" ID="USER_CANCEL_ANY" {?user_cancel_any}><LABEL FOR="USER_CANCEL_ANY">  Tillad brugere at annullere alle jobs (ikke kun deres egne)</LABEL><BR>
-    <INPUT TYPE="CHECKBOX" NAME="PRESERVE_JOBS" ID="PRESERVE_JOBS" {?preserve_jobs}><LABEL FOR="PRESERVE_JOBS">  Bevar jobhistorik</LABEL><BR>
+    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<INPUT TYPE="CHECKBOX" NAME="REMOTE_ANY" ID="REMOTE_ANY" VALUE="CHECKED" {?remote_any}><LABEL FOR="REMOTE_ANY">  Tillad udskrivning fra internettet</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/da/admin.tmpl:45]: VALUE for checkbox is not valid.

File: templates/da/admin.tmpl [hunk 10]
```diff
@@ -38,36 +38,36 @@
...
+    <INPUT TYPE="CHECKBOX" NAME="PRESERVE_JOBS" ID="PRESERVE_JOBS" VALUE="CHECKED" {?preserve_jobs}><LABEL FOR="PRESERVE_JOBS">  Bevar jobhistorik</LABEL><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Maksimum jobs (0 for ubegrænset)\:
     <INPUT TYPE="TEXT" NAME="MAX_JOBS" VALUE="{?max_jobs}" SIZE="6"><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bevar metadata\:
     <INPUT TYPE="TEXT" NAME="PRESERVE_JOB_HISTORY" VALUE="{?preserve_job_history}" SIZE="6"><BR>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bevar dokumenter\:
     <INPUT TYPE="TEXT" NAME="PRESERVE_JOB_FILES" VALUE="{?preserve_job_files}" SIZE="6"><BR>
-    <INPUT TYPE="CHECKBOX" NAME="DEBUG_LOGGING" ID="DEBUG_LOGGING" {?debug_logging}><LABEL FOR="DEBUG_LOGGING">  Gem fejlretningsinformation til fejlsøgning</LABEL><BR>
+    <INPUT TYPE="CHECKBOX" NAME="DEBUG_LOGGING" ID="DEBUG_LOGGING" VALUE="CHECKED" {?debug_logging}><LABEL FOR="DEBUG_LOGGING">  Gem fejlretningsinformation til fejlsøgning</LABEL><BR>
```
Comment (michaelrsweet) [inline templates/da/admin.tmpl:57]: VALUE for checkbox is not valid.

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
See comments - main issue is the template changes - VALUE isn't valid for checkboxes, but the HIDDEN changes are OK.

File: cgi-bin/admin.c (hunk 1 above)
Comment (zdohnal) [reply cgi-bin/admin.c:1399]: Aha, note for myself - ```parse_variable()``` :) .

File: templates/add-printer.tmpl (hunk 2 above)
Comment (zdohnal) [reply templates/add-printer.tmpl:35]: @michaelrsweet Why isn't it valid? It looks like the mean how to change what is returned in form if the checkbox is checked based on this page https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox .

Additionally, we save the same value into the checkbox variables in ```do_menu()``` if the option is on, so IMHO we should get the same value from the form if user checks the option. If the value is not set for checkbox input type, the incoming value will always be "ON", so we would have to adjust admin CGI script accordingly if we don't use VALUE attribute.

Comment (michaelrsweet) [reply templates/add-printer.tmpl:35]: Sorry, I misremembered the current HTML spec WRT checkboxes. But since the default value is CHECKED and we want it to return CHECKED, I don't see a reason to add the VALUE everywhere there is a checkbox.

Comment (zdohnal) [reply templates/add-printer.tmpl:35]: @michaelrsweet  If there is no VALUE attribute (meaning VALUE="smth"), the form will contain NAME="ON" if the checkbox is checked, so in our case here PRINTER_IS_SHARED="ON". IIUC ```{PRINTER_IS_SHARED=1?CHECKED:}``` decides only what will be showed when the page is loaded, but not what will be sent in form if the box stays checked.

Comment (michaelrsweet) [reply templates/add-printer.tmpl:35]: Sigh, ok well then we either add the value attribute or allow any value to be treated as checked in `cgiGetCheckbox`.

Comment (zdohnal) [reply templates/add-printer.tmpl:35]: I would add the value attribute into the templates - we already set the checkbox variables in CGI to "checked" already before this change, so it can be consistent.

File: templates/admin.tmpl (hunk 3 above)
Comment (zdohnal) [reply templates/admin.tmpl:42]: Explained in the previous comment.

File: templates/admin.tmpl (hunk 5 above)
Comment (zdohnal) [reply templates/admin.tmpl:57]: Explained in the previous comment.

File: templates/da/add-printer.tmpl (hunk 7 above)
Comment (zdohnal) [reply templates/da/add-printer.tmpl:35]: Explained in the previous comment.

File: templates/da/admin.tmpl (hunk 8 above)
Comment (zdohnal) [reply templates/da/admin.tmpl:42]: Explained in the previous comment.

File: templates/admin.tmpl (hunk 6 above)
Comment (zdohnal) [reply templates/admin.tmpl:65]: Explained in the previous comment.

File: templates/admin.tmpl (hunk 4 above)
Comment (zdohnal) [reply templates/admin.tmpl:45]: Explained in the previous comment.

File: templates/da/admin.tmpl (hunk 9 above)
Comment (zdohnal) [reply templates/da/admin.tmpl:45]: Explained in the previous comment.

File: templates/da/admin.tmpl (hunk 10 above)
Comment (zdohnal) [reply templates/da/admin.tmpl:57]: Explained in the previous comment.

File: templates/add-printer.tmpl (hunk 2 above)
Comment (zdohnal) [reply templates/add-printer.tmpl:35]: @michaelrsweet so I reverted the 1d -> 86400 change, otherwise the changes are the same since it already contained value attribute additions. Ready for review.

**Review by michaelrsweet — APPROVED** [review]
ok
