### PR TITLE
request.c: Use errno only if it is non-zero (fixes #893)

### LINKED ISSUE #893: libcups returns success if scheduler does not send data in time (f.e. cups-driverd times out)
**Describe the bug**
"There was an error during cups operation: success" when adding a remote printer using LPR. In cups webGUI, I'd entered the same printer address than in the Linux Mint add printer GUI, nothing happens when clicking "Continue". The page just get reloaded.

**To Reproduce**
Steps to reproduce the behavior on CUPS webGUI:
1. Go to 'Add printers'
2. Fill with info
3. Click continue 
4. nothing happens.

Steps to reproduce the behavior on Linux Mint add printers:
1. Go to 'Add printers'
2. Fill with info
3. Click continue 
4. "There was an error during cups operation: success".

**Expected behavior**
On both Linux GUI and CUPS webGUI, the select driver interface supposed to show up.

**Screenshots**
Screenshot at 2024-02-14 19-50-20

**System Information:**
 - OS and its version: Linux Mint 21.3 x64
 - CUPS version 2.4.1

**Additional context**
I did search and, there was similar issues but not exactly what covering my problem. 
I do have 3 other printers on the system. 
Since few time, I do have the same error when adding other printers as well.

### PR DESCRIPTION
**Pull request by zdohnal**
In case of internal errors, we use errno for generating error message, but there are cases (like operation timeout for listing drivers or models) when errno is zero.
We should take error from `http->error` if errno is zero, falling back to `Internal Server Error` if even `http->error` is 0 and still we have HTTP_STATUS_ERROR.

Fixes #893

### CODE REVIEW

File: cups/request.c [hunk 1]
```diff
@@ -248,6 +248,9 @@ cupsDoIORequest(http_t     *http,	/* I - Connection to server or @code CUPS_HTTP
         (status >= HTTP_STATUS_BAD_REQUEST && status != HTTP_STATUS_UNAUTHORIZED &&
 	 status != HTTP_STATUS_UPGRADE_REQUIRED))
     {
+      if (!errno)
```
Comment (michaelrsweet) [inline cups/request.c:251]: This would only be for `HTTP_STATUS_ERROR`, so it might be better to update `_cupsSetHTTPError` to accept a `http_t *` argument and look at `http->error` instead of `errno`…

File: cups/request.c [hunk 2]
```diff
@@ -1196,7 +1199,7 @@ _cupsSetHTTPError(http_status_t status)	/* I - HTTP status code */
         break;
 
     case HTTP_STATUS_ERROR :
-	_cupsSetError(IPP_STATUS_ERROR_INTERNAL, strerror(errno), 0);
+	_cupsSetError(IPP_STATUS_ERROR_INTERNAL, errno != 0 ? strerror(errno) : "Internal Server Error", 0);
```
Comment (michaelrsweet) [inline cups/request.c:1202]: Add a `http` argument and check `http->error`.

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
See comments. I think we need a little code refactoring here…

File: cups/request.c (hunk 1 above)
Comment (zdohnal) [reply cups/request.c]: Unfortunately I found out we have both use cases in the code - errno is used when we track before we establish connection (in cups/http-addr.c, cups/ipp.c or cups/http.c), so we need to support both :( . I've updated the PR accordingly.

File: cups/http-addr.c [hunk 3]
```diff
@@ -207,7 +207,7 @@ httpAddrListen(http_addr_t *addr,	// I - Address to bind to
   // Create the socket and set options...
   if ((fd = socket(addr->addr.sa_family, SOCK_STREAM, 0)) < 0)
   {
-    _cupsSetHTTPError(HTTP_STATUS_ERROR);
+    _cupsSetHTTPError(NULL, HTTP_STATUS_ERROR);
```
Comment (michaelrsweet) [inline cups/http-addr.c:210]: Use `_cupsSetError(IPP_STATUS_ERROR_INTERNAL, strerror(errno), 0);` for these cases, that way `_cupsSetHTTPError` can be specific to `http_t` errors.

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
See comments.

File: cups/request.c (hunk 1 above)
Comment (zdohnal) [reply cups/request.c]: Applied.

File: cups/http-addr.c (hunk 3 above)
Comment (zdohnal) [reply cups/http-addr.c]: ok, thanks! Applied.

File: cups/request.c [hunk 4]
```diff
@@ -1151,7 +1151,8 @@ _cupsSetError(ipp_status_t status,	/* I - IPP status code */
  */
 
 void
-_cupsSetHTTPError(http_status_t status)	/* I - HTTP status code */
+_cupsSetHTTPError(http_t	*http,	/* I - HTTP connection to server or @code CUPS_HTTP_DEFAULT@ */
```
Comment (michaelrsweet) [inline cups/request.c:1154]: This code shouldn't support `CUPS_HTTP_DEFAULT` since that's for public APIs to map to the current thread's domain socket.

File: cups/request.c [hunk 5]
```diff
@@ -1196,8 +1197,8 @@ _cupsSetHTTPError(http_status_t status)	/* I - HTTP status code */
         break;
 
     case HTTP_STATUS_ERROR :
-	_cupsSetError(IPP_STATUS_ERROR_INTERNAL, strerror(errno), 0);
-        break;
+	_cupsSetError(IPP_STATUS_ERROR_INTERNAL, http && http->error != 0 ? strerror(http->error) : "Internal Server Error", 0);
```
Comment (michaelrsweet) [inline cups/request.c:1200]: and here assume that `http` is not `NULL`, which we can do because a) it is a private API and b) all of the callers already ensure the pointer is not `NULL`.

**Review by michaelrsweet — CHANGES_REQUESTED** [review]
A few small nits - see comments.

File: cups/request.c (hunk 4 above)
Comment (zdohnal) [reply cups/request.c]: Ok, fixed.

File: cups/request.c (hunk 5 above)
Comment (zdohnal) [reply cups/request.c]: Ok, I was thinking around the lines what static analyzers can complaint about and protecting the code even from ourselves (I can forget that I should not pass NULL there, so a protection against it :D ), but yeah, we can assume that I don't forget :D .

**Review by michaelrsweet — APPROVED** [review]
+1

**Comment by andi34** [comment]
Currently breaks the build 

```
ipp.c: In function ‘ippReadIO’:
ipp.c:3211:1: error: invalid use of void expression
 3211 | +             _cupsSetError(IPP_STATUS_ERROR_INTERNAL, _("Unable to allocate IPP attribute."), 1);
      | ^
make[1]: *** [../Makedefs:271: ipp.o] Error 1
make[1]: Leaving directory '/home/runner/work/cups/cups/cups'
make: *** [Makefile:43: all] Error 1
```

**Comment by zdohnal** [comment]
@andi34 ouch! Thanks! I was too eager there, it should be fixed now.
